import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Supabase CLI — do not lint.
    "src/lib/types/database.ts",
  ]),
  // Fast lint-time signal against pulling server-only code into a component
  // bundle. The build-time backstop is the `import "server-only"` marker in
  // these modules, which also catches the *transitive* case ESLint can't see
  // (e.g. a component importing a data module that in turn imports these).
  {
    files: ["src/components/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/lib/supabase/server", "@/lib/modules/fetch"],
              allowTypeImports: true,
              message:
                "Server-only modules depend on next/headers and must not be imported by components. Fetch in a Server Component or page and pass data down as props.",
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
